### ISSUE TITLE
[BUG] Приложение показывает пары в выходные дни

### ISSUE THREAD

**Issue by horanchikk** [Ethosa/KTC#21]
В воскресенье показывает пары на понедельник.

Необходимо, чтобы в выходные дни вообще не выделялись пары.

- Девайс: Redmi Note 7
- OS: Android 12, прошивка Syberia
- Версия приложения 0.9.0

Скрин ниже:

![Screenshot_20220918-110948_KTC](https://user-images.githubusercontent.com/46918417/190885484-298081fb-8e6e-4275-9875-2b70f4953be0.png)

**Comment by horanchikk** [comment]
не пофикшено.

**Comment by Ethosa** [comment]
ок
