### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by horanchikk** [Ethosa/KTC#23]
Предлагаю сменить цвет кнопок по краям на более светлый, т.к. они сливаются с фоном и не сразу заметны.

Скрин ниже:

![Screenshot_20220918-112400_KTC](https://user-images.githubusercontent.com/46918417/190885701-a8b16a0a-7310-4166-9d5a-5a24e563d104.png)

**Comment by Ethosa** [comment]
как это выглядит в светлой теме?
